export const PLAYER = {
  SET_ID: 'PLAYER_SET_ID',
  SET_NAME: 'PLAYER_SET_NAME',
  SET_COLOR: 'PLAYER_SET_COLOR',
  RESET: 'PLAYER_RESET',
};

export const GAME = {
  SET_SETTINGS: 'GAME_SET_SETTINGS',
  SET_JOINED_GAME: 'GAME_SET_JOINED_GAME',
  ADD_PLAYER: 'GAME_ADD_PLAYER',
  RESET: 'GAME_RESET',
};
